### ISSUE TITLE
TWRP-3.6.1 loses ROOT

### ISSUE THREAD

**Issue by tfft** [TeamWin/android_bootable_recovery#222]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: hlte
**TWRP version**: 3.6.1 (official)

#### _WHAT STEPS WILL REPRODUCE THE PROBLEM?_
I used the "Official TWRP App" to update to 3.6.1 - all went as expected and was completed successfully.  Subsequently I updated my ROM to latest (lineage-18.1-20220312-nightly-hlte-signed.zip), something that I've done 100s of times but this time around my Magisk (24.3) seems to have been "uninstalled" and root was lost (due to 'unable to mount /system' per what I saw on the screen).

#### _WHAT IS THE EXPECTED RESULT?_
I expected 3.6.1 to function like 3.6.0 where root continued to be maintained and Magisk was properly taken care of.

#### _WHAT HAPPENS INSTEAD?_
Root ability is lost and I had to reinstall Magisk (24.3) and root my device all over again.

#### _ADDITIONAL INFORMATION_
I had to reboot a number of times to address the loss of root issue so most of the logs were overwritten execept for the recovery.log (note the "mount: can't find /system in /etc/fstab").

`/tmp/recovery.log`: https://paste.ee/p/7Dmih

**Comment by boringhexi** [comment]
Okay, so the way I understand it is that when LineageOS updates, it *always* wipes Magisk, every single time... but then TWRP takes over and reinstalls Magisk using Magisk's own recovery installer script.

> (note the "mount: can't find /system in /etc/fstab").

So, this is the bug I've been dealing with for the last hour, too! It causes the Magisk recovery installer script to fail. Long story short, the bug is described at https://github.com/topjohnwu/Magisk/issues/5530, it's already fixed in Magisk Canary, and you can expect it to be fixed in Magisk release 24.4 (or whatever the next stable release is).

**Comment by tfft** [comment]
Thanks @boringhexi for the follow-up and linking the 2 threads.  Magisk has confirmed that it is a bug on their end - so whomever is tracking these bugs - consider this one closed.
